spring:
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/test
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
logging:
  pattern:
    console: "%d [%5p] [%t] %c{3}.%M:%L - %m%n"
  level:
    root: ERROR
    com:
      gargjayesh: DEBUG